---
region_config:
  name: "Norte"
  code: "NTE"
  timezone: "America/Santiago"
  backup_window_start: "01:00"
  backup_window_end: "03:00"
  backup_order: 1
  notify_escalation:
    - "netops-norte@internal.local"
    - "netops@internal.local"

network:
  management_subnet: "10.100.0.0/22"
  mgmt_gateway: "10.100.0.1"
  dns_servers:
    - "10.100.0.10"
    - "10.100.0.11"
  ntp_servers:
    - "10.100.0.20"
    - "10.100.0.21"
  syslog_server: "10.100.0.30"
